# Generated by Django 6.1.1 on 2026-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0003_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
