# Generated by Django 6.1.1 on 2026-09-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0007_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='eventsapp.vendorprofile'),
        ),
    ]
